version: 2

jobs:
  build:
    docker:
      - image: archlinux
    steps:
      - checkout
      - run:
          name: Install required tools
          command: "pacman -Sy --noconfirm base base-devel gcc git cmake doxygen gtest clang iex-git"

      - run:
          name: Configure
          command: |
            rm -rf build
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON -DBUILD_DOCUMENTATION:BOOL=ON -DBUILD_TESTING:BOOL=ON -DENABLE_CXX_WARNINGS:BOOL=ON ..
      - run:
          name: Style
          command: "./lint.sh"
      - run:
          name: Compile
          command: "cmake --build build/"
      - run:
          name: Unit Test
          command: "././build/invport/test/unit_test"
